version: '3'
services:
  lyceum_nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: lyceum_nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
      - MONGO_URL=$MONGO_URL
      - WAIT_HOSTS=lyceum_mongo:27017
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    depends_on:
      - lyceum_mongo
  lyceum_mongo:
    image: mongo:3.6.20-xenial
    container_name: lyceum_mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./dump:/dump
      - ./dbdata:/data/db
    ports:
      - 27017:27017 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

#volumes:
  #dbdata:
  #dump:
  #node_modules: